apiVersion: v2
name: field-content-demo
description: App of Apps - Deploy OpenShift Pipelines and other components via ArgoCD
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Sebastien Lallemand
