site:
  title: "Comment créer votre propre démo sur RHDP"
  url: https://github.com/slallemand/rhdp-field-content-demo
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/patternfly-6/ui-bundle.zip
    snapshot: true

runtime:
  fetch: true
  cache_dir: ./.cache/antora

output:
  dir: ./www
