# Injected by RHDP
deployer:
  domain: apps.cluster-example.redhatworkshops.io

# Operators to deploy
operators:
  openshift-pipelines:
    enabled: true
    name: openshift-pipelines-operator-rh
    channel: latest
    source: redhat-operators
    namespace: openshift-operators

  web-terminal:
    enabled: true
    name: web-terminal
    channel: fast
    source: redhat-operators
    namespace: openshift-operators

