runtime:
  cache_dir: ./.cache/antora

site:
  title: How to customise your own demo on RHDP
  url: /
  start_page: modules::index.adoc

content:
  sources:
    - url: https://github.com/slallemand/rhdp-field-content-demo.git
      start_path: showroom-content
      branches:
        - main

ui:
  bundle:
    url: https://github.com/rhpds/nookbag/releases/download/nookbag-v0.3.6/nookbag-v0.3.6.zip

output:
  dir: ./gh-pages
