{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "showroom-demo.fullname" . }}
  labels:
    {{- include "showroom-demo.labels" . | nindent 4 }}
    demo.redhat.com/application: "field-content"
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- else }}
  host: showroom-demo-{{ .Release.Namespace }}.apps.{{ .Values.deployer.domain }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "showroom-demo.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
