{{- if .Values.userInfo.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "showroom-demo.fullname" . }}-credentials
  labels:
    {{- include "showroom-demo.labels" . | nindent 4 }}
    demo.redhat.com/application: "field-content"
type: Opaque
stringData:
  password: {{ .Values.userInfo.password | quote }}
{{- end }}
