{{- if .Values.components.openshiftPipelines.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-openshift-pipelines
  namespace: {{ .Values.argocd.namespace }}
  labels:
    demo.redhat.com/application: "field-content"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  source:
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.revision }}
    path: components/openshift-pipelines
    helm:
      releaseName: openshiftPipelines
      valuesObject:
        subscription: {{ toYaml .Values.components.openshiftPipelines.subscription | nindent 10 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.components.openshiftPipelines.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
{{- end }}
