{{- range $name, $config := .Values.helmCharts }}
{{- if $config.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: openshift-gitops
  labels:
    demo.redhat.com/application: "field-content"
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $config.wave | default 0 }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ $config.source.repoURL }}
    targetRevision: {{ $config.source.targetRevision }}
    {{- if $config.source.path }}
    path: {{ $config.source.path }}
    {{- end }}
    {{- if $config.source.chart }}
    chart: {{ $config.source.chart }}
    {{- end }}
    {{- if $config.values }}
    helm:
      valuesObject: {{ toYaml $config.values | nindent 8 }}
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $config.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
{{- end }}
